param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [switch]$UpdateManifest,
    [switch]$CopyToGameRoot
)

$ErrorActionPreference = 'Stop'

function Get-Adler32 {
    param([byte[]]$Bytes)

    [uint32]$a = 1
    [uint32]$b = 0

    foreach ($byte in $Bytes) {
        $a = ($a + $byte) % 65521
        $b = ($b + $a) % 65521
    }

    $value = [uint32]((($b -shl 16) + $a) -band 0xffffffff)
    return $value.ToString('x8')
}

function Get-LuaLongString {
    param([string]$Text)

    $equals = ''
    while ($Text.Contains("]$equals]")) {
        $equals += '='
    }

    return "[$equals[$Text]$equals]"
}

function Get-LuaQuotedString {
    param([string]$Text)

    $Text = $Text.Replace('\', '\\')
    $Text = $Text.Replace('"', '\"')
    $Text = $Text.Replace("`r", '\r')
    $Text = $Text.Replace("`n", '\n')
    return '"' + $Text + '"'
}

function Get-RelativeLuaModuleName {
    param(
        [string]$RootPath,
        [string]$FilePath
    )

    $rootFullPath = [System.IO.Path]::GetFullPath($RootPath).TrimEnd('\', '/') + [System.IO.Path]::DirectorySeparatorChar
    $fileFullPath = [System.IO.Path]::GetFullPath($FilePath)

    if (-not $fileFullPath.StartsWith($rootFullPath, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "File is outside root: $FilePath"
    }

    $relative = $fileFullPath.Substring($rootFullPath.Length)
    $relative = $relative.Replace('\', '/')
    return $relative.Substring(0, $relative.Length - 4)
}

$loaderPath = Join-Path $Root 'Pasthetic loader.lua'
$allinoneFileName = 'Pasthetic_allinone.lua'
$bundleFileName = 'Pasthetic_allinone_bundle.lua'
$bootstrapPath = Join-Path $Root $allinoneFileName
$outputPath = Join-Path $Root $bundleFileName
$modulesRoot = Join-Path $Root 'pasthetic'
$manifestPath = Join-Path $Root 'manifest.json'
$updatesPath = Join-Path $Root 'updates.json'

if (-not (Test-Path -LiteralPath $loaderPath)) {
    throw "Missing loader: $loaderPath"
}

if (-not (Test-Path -LiteralPath $modulesRoot)) {
    throw "Missing module directory: $modulesRoot"
}

$loader = [System.IO.File]::ReadAllText($loaderPath)
$loader = $loader -replace "`r`n", "`n"

$allinoneVersion = 'unknown'
if (Test-Path -LiteralPath $updatesPath) {
    $updates = Get-Content -LiteralPath $updatesPath -Raw | ConvertFrom-Json
    if ($null -ne $updates.entries -and $updates.entries.Count -gt 0 -and -not [string]::IsNullOrWhiteSpace($updates.entries[0].version)) {
        $allinoneVersion = [string]$updates.entries[0].version
    }
}

$suffixMarker = "local ffi = require 'ffi'"
$suffixIndex = $loader.IndexOf($suffixMarker)
if ($suffixIndex -lt 0) {
    throw "Cannot find loader suffix marker: $suffixMarker"
}

$loaderSuffix = $loader.Substring($suffixIndex)
$moduleFiles = Get-ChildItem -LiteralPath $modulesRoot -Recurse -File -Filter '*.lua' |
    Sort-Object { Get-RelativeLuaModuleName -RootPath $Root -FilePath $_.FullName }

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine('-- Pasthetic all-in-one generated from local split modules.')
[void]$builder.AppendLine('-- Do not edit this file by hand; regenerate it with tools/build_allinone.ps1.')
[void]$builder.AppendLine('local __pasthetic_allinone = true')
[void]$builder.AppendLine("local __pasthetic_disable_allinone_update = rawget(_G, '__pasthetic_allinone_bootstrap') == true")
[void]$builder.AppendLine(("local __pasthetic_allinone_version = {0}" -f (Get-LuaQuotedString -Text $allinoneVersion)))
[void]$builder.AppendLine(("local __pasthetic_allinone_target_path = {0}" -f (Get-LuaQuotedString -Text ('.\' + $allinoneFileName))))
[void]$builder.AppendLine("local PASTHETIC_GIT_URL = 'https://github.com/Garagoro/Pasthetic'")
[void]$builder.AppendLine("local function log_loader_reinstall_hint()")
[void]$builder.AppendLine("    if client ~= nil and client.color_log ~= nil then")
[void]$builder.AppendLine("        client.color_log(250, 50, 75, '[Pasthetic] \0')")
[void]$builder.AppendLine("        client.color_log(255, 255, 255, 'Redownload the loader from GitHub: ' .. PASTHETIC_GIT_URL)")
[void]$builder.AppendLine("    end")
[void]$builder.AppendLine("end")
[void]$builder.AppendLine('local __pasthetic_embedded_modules = {')

foreach ($file in $moduleFiles) {
    $moduleName = Get-RelativeLuaModuleName -RootPath $Root -FilePath $file.FullName
    $source = [System.IO.File]::ReadAllText($file.FullName)
    $source = $source -replace "`r`n", "`n"
    $longString = Get-LuaLongString -Text $source
    [void]$builder.AppendLine(("    [{0}] = {1}," -f (Get-LuaQuotedString -Text $moduleName), $longString))
}

[void]$builder.AppendLine('}')
[void]$builder.AppendLine('local __pasthetic_embedded_files = {}')
[void]$builder.AppendLine('for __name, __source in pairs(__pasthetic_embedded_modules) do')
[void]$builder.AppendLine("    __pasthetic_embedded_files[__name .. '.lua'] = __source")
[void]$builder.AppendLine("    __pasthetic_embedded_files[(__name .. '.lua'):gsub('/', '\\')] = __source")
[void]$builder.AppendLine('end')
[void]$builder.AppendLine('local __pasthetic_real_readfile = readfile')
[void]$builder.AppendLine('local function __pasthetic_readfile(path)')
[void]$builder.AppendLine("    if type(path) == 'string' then")
[void]$builder.AppendLine("        local normalized = path:gsub('^%.[/\\]', '')")
[void]$builder.AppendLine('        local direct = __pasthetic_embedded_files[normalized]')
[void]$builder.AppendLine('        if direct ~= nil then return direct end')
[void]$builder.AppendLine("        local slash = normalized:gsub('\\', '/')")
[void]$builder.AppendLine('        direct = __pasthetic_embedded_files[slash]')
[void]$builder.AppendLine('        if direct ~= nil then return direct end')
[void]$builder.AppendLine("        direct = __pasthetic_embedded_files[slash:gsub('/', '\\')]")
[void]$builder.AppendLine('        if direct ~= nil then return direct end')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    if __pasthetic_real_readfile ~= nil then')
[void]$builder.AppendLine('        return __pasthetic_real_readfile(path)')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    return nil')
[void]$builder.AppendLine('end')
[void]$builder.AppendLine('local function can_read_file(path)')
[void]$builder.AppendLine('    if __pasthetic_real_readfile == nil then')
[void]$builder.AppendLine('        return false')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('    local ok, result = pcall(__pasthetic_real_readfile, path)')
[void]$builder.AppendLine("    return ok and type(result) == 'string'")
[void]$builder.AppendLine('end')
[void]$builder.AppendLine("local LOCAL_PREFIX = can_read_file('pasthetic\\core.lua') and '' or (can_read_file('pasthetic\\pasthetic\\core.lua') and 'pasthetic\\' or '')")
[void]$builder.AppendLine('local function local_path(path)')
[void]$builder.AppendLine("    if LOCAL_PREFIX == '' or type(path) ~= 'string' or path == '' then")
[void]$builder.AppendLine('        return path')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    return LOCAL_PREFIX .. path')
[void]$builder.AppendLine('end')
[void]$builder.AppendLine('local function require_pasthetic_module(name)')
[void]$builder.AppendLine('    if package ~= nil and package.loaded ~= nil then')
[void]$builder.AppendLine('        package.loaded[name] = nil')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    local source = __pasthetic_embedded_modules[name]')
[void]$builder.AppendLine("    local path = name:gsub('/', '\\') .. '.lua'")
[void]$builder.AppendLine('    if source == nil then')
[void]$builder.AppendLine('        source = __pasthetic_readfile(local_path(path))')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    if source == nil then')
[void]$builder.AppendLine("        local nested_path = 'pasthetic\\' .. path")
[void]$builder.AppendLine('        source = __pasthetic_readfile(local_path(nested_path))')
[void]$builder.AppendLine('        if source ~= nil then path = nested_path end')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    if source ~= nil then')
[void]$builder.AppendLine("        local chunk, load_error = loadstring(source, '@' .. path)")
[void]$builder.AppendLine('        if chunk == nil then log_loader_reinstall_hint(); error(load_error) end')
[void]$builder.AppendLine('        local ok, result = pcall(chunk)')
[void]$builder.AppendLine('        if not ok then log_loader_reinstall_hint(); error(result) end')
[void]$builder.AppendLine('        if package ~= nil and package.loaded ~= nil then package.loaded[name] = result end')
[void]$builder.AppendLine('        return result')
[void]$builder.AppendLine('    end')
[void]$builder.AppendLine('    local ok, result = pcall(require, name)')
[void]$builder.AppendLine('    if ok then return result end')
[void]$builder.AppendLine('    log_loader_reinstall_hint()')
[void]$builder.AppendLine('    error(result)')
[void]$builder.AppendLine('end')
[void]$builder.AppendLine('')
[void]$builder.Append($loaderSuffix)

$output = $builder.ToString() -replace "`r`n", "`n"
[System.IO.File]::WriteAllText($outputPath, $output, [System.Text.UTF8Encoding]::new($false))

$bootstrap = @"
-- Pasthetic all-in-one bootstrap.
-- This small file downloads and runs the generated bundle from GitHub.
local BOOTSTRAP_VERSION = "__VERSION__"
local CACHE_PATH = "pasthetic\\Pasthetic_allinone.cache.lua"
local MANIFEST_URLS = {
    "https://raw.githubusercontent.com/Garagoro/Pasthetic/refs/heads/main/manifest.json",
    "https://raw.githubusercontent.com/Garagoro/Pasthetic/main/manifest.json",
}
local BASE_URLS = {
    "https://raw.githubusercontent.com/Garagoro/Pasthetic/refs/heads/main/",
    "https://raw.githubusercontent.com/Garagoro/Pasthetic/main/",
}

local function log(r, g, b, msg)
    if client ~= nil and client.color_log ~= nil then
        client.color_log(180, 100, 255, "[Pasthetic] \0")
        client.color_log(r or 255, g or 255, b or 255, msg)
    end
end

local function tohex32(n)
    local chars = "0123456789abcdef"
    local out = {}
    for i = 8, 1, -1 do
        local d = n % 16
        out[i] = chars:sub(d + 1, d + 1)
        n = (n - d) / 16
    end
    return table.concat(out)
end

local function adler32(data)
    local a, b = 1, 0
    for i = 1, #data do
        a = (a + data:byte(i)) % 65521
        b = (b + a) % 65521
    end
    return tohex32((b * 65536 + a) % 4294967296)
end

local function url_path(path)
    if type(path) ~= "string" then return "" end
    path = path:gsub("\\", "/")
    return (path:gsub("([^%w%-%._~/])", function(char)
        return ("%%%02X"):format(char:byte())
    end))
end

local function decode_manifest(body)
    if type(body) ~= "string" or body == "" then return nil end
    body = body:gsub("^\239\187\191", ""):gsub("^%s+", "")
    local parser = json ~= nil and (json.parse or json.decode) or nil
    if type(parser) ~= "function" then return nil end
    local ok, decoded = pcall(parser, body)
    if not ok or type(decoded) ~= "table" then return nil end
    return decoded
end

local function compare_versions(left, right)
    left = tostring(left or "")
    right = tostring(right or "")
    local a, b = {}, {}
    for part in left:gmatch("%d+") do a[#a + 1] = tonumber(part) or 0 end
    for part in right:gmatch("%d+") do b[#b + 1] = tonumber(part) or 0 end
    for i = 1, math.max(#a, #b) do
        local av, bv = a[i] or 0, b[i] or 0
        if av ~= bv then return av > bv and 1 or -1 end
    end
    return 0
end

local function get_artifact(manifest)
    local artifact = manifest ~= nil and manifest.artifacts ~= nil and manifest.artifacts.allinone or nil
    if type(artifact) == "table" and type(artifact.path) == "string" then
        return artifact
    end
    return nil
end

local function http_get(url, callback)
    local ok, http = pcall(require, "gamesense/http")
    if not ok or type(http) ~= "table" or type(http.get) ~= "function" then
        return false
    end
    return pcall(http.get, url, function(success, response)
        local status, body
        if type(success) == "table" and response == nil then
            response = success
            success = true
        elseif type(success) == "string" and response == nil then
            body = success
            status = 200
            success = true
        end
        if type(response) == "table" then
            status = response.status or response.status_code or response.code
            body = response.body or response.data or response.content or response.text
        elseif type(response) == "string" and body == nil then
            status = 200
            body = response
        end
        callback(success and (status == nil or status == 200 or status == "200") and body or nil)
    end)
end

local function run_bundle(source, label)
    local loader = loadstring or load
    if type(loader) ~= "function" then
        log(250, 50, 75, "loadstring unavailable")
        return false
    end
    local chunk, err = loader(source, "@" .. (label or "Pasthetic_allinone_bundle.lua"))
    if chunk == nil then
        log(250, 50, 75, "bundle syntax error: " .. tostring(err))
        return false
    end
    _G.__pasthetic_allinone_bootstrap = true
    local ok, runtime_err = pcall(chunk)
    _G.__pasthetic_allinone_bootstrap = nil
    if not ok then
        error(runtime_err)
    end
    return true
end

local function run_cache(reason)
    if readfile == nil then
        log(250, 50, 75, reason .. "; no cached bundle")
        return
    end
    local ok, cached = pcall(readfile, CACHE_PATH)
    if ok and type(cached) == "string" and cached ~= "" then
        log(255, 255, 255, reason .. "; loading cached all-in-one")
        run_bundle(cached, CACHE_PATH)
    else
        log(250, 50, 75, reason .. "; no cached bundle")
    end
end

local function get_base_urls(manifest)
    local urls = {}
    if type(manifest) == "table" and type(manifest.base_urls) == "table" then
        for i = 1, #manifest.base_urls do
            if type(manifest.base_urls[i]) == "string" then
                urls[#urls + 1] = manifest.base_urls[i]
            end
        end
    end
    if type(manifest) == "table" and type(manifest.base_url) == "string" then
        urls[#urls + 1] = manifest.base_url
    end
    for i = 1, #BASE_URLS do urls[#urls + 1] = BASE_URLS[i] end
    return urls
end

local function fetch_best_manifest(callback)
    local index = 1
    local best_manifest, best_body
    local function next_url()
        local url = MANIFEST_URLS[index]
        if url == nil then
            callback(best_manifest, best_body)
            return
        end
        index = index + 1
        if not http_get(url, function(body)
            local manifest = decode_manifest(body)
            local artifact = get_artifact(manifest)
            local best_artifact = get_artifact(best_manifest)
            if artifact ~= nil and (
                best_artifact == nil or compare_versions(artifact.version, best_artifact.version) > 0
            ) then
                best_manifest = manifest
                best_body = body
            end
            next_url()
        end) then
            next_url()
        end
    end
    next_url()
end

local function fetch_bundle(manifest, artifact)
    local base_urls = get_base_urls(manifest)
    local remote_path = url_path(artifact.path)
    local index = 1
    local function next_url()
        local base_url = base_urls[index]
        if base_url == nil then
            run_cache("bundle download failed")
            return
        end
        index = index + 1
        if not http_get(base_url .. remote_path, function(body)
            if type(body) == "string"
                and (type(artifact.size) ~= "number" or #body == artifact.size)
                and (type(artifact.checksum) ~= "string" or adler32(body) == artifact.checksum)
            then
                if writefile ~= nil then pcall(writefile, CACHE_PATH, body) end
                run_bundle(body, artifact.path)
            else
                next_url()
            end
        end) then
            next_url()
        end
    end
    next_url()
end

log(255, 255, 255, "loading all-in-one...")
fetch_best_manifest(function(manifest)
    local artifact = get_artifact(manifest)
    if artifact == nil then
        run_cache("manifest download failed")
        return
    end
    fetch_bundle(manifest, artifact)
end)
"@
$bootstrap = $bootstrap.Replace('__VERSION__', $allinoneVersion)
$bootstrap = $bootstrap -replace "`r`n", "`n"
[System.IO.File]::WriteAllText($bootstrapPath, $bootstrap, [System.Text.UTF8Encoding]::new($false))

if ($UpdateManifest) {
    if (-not (Test-Path -LiteralPath $manifestPath)) {
        throw "Missing manifest: $manifestPath"
    }

    $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
    $manifestPaths = @{}

    foreach ($entry in $manifest.files) {
        if ($null -ne $entry.path) {
            if ([string]$entry.path -eq 'Pasthetic allinone.lua') {
                $entry.path = $allinoneFileName
            }
            $manifestPaths[[string]$entry.path] = $true
        }
    }

    if (-not $manifestPaths.ContainsKey($allinoneFileName)) {
        $manifest.files += [pscustomobject]@{
            path = $allinoneFileName
            size = 0
            checksum = ''
        }
        $manifestPaths[$allinoneFileName] = $true
    }

    if (-not $manifestPaths.ContainsKey($bundleFileName)) {
        $manifest.files += [pscustomobject]@{
            path = $bundleFileName
            size = 0
            checksum = ''
        }
        $manifestPaths[$bundleFileName] = $true
    }

    foreach ($file in $moduleFiles) {
        $modulePath = (Get-RelativeLuaModuleName -RootPath $Root -FilePath $file.FullName) + '.lua'

        if (-not $manifestPaths.ContainsKey($modulePath)) {
            $manifest.files += [pscustomobject]@{
                path = $modulePath
                size = 0
                checksum = ''
            }
            $manifestPaths[$modulePath] = $true
        }
    }

    foreach ($entry in $manifest.files) {
        if ($null -eq $entry.path -or $entry.path -like '*..*' -or $entry.path -match '^[a-zA-Z]:') {
            continue
        }

        $targetPath = Join-Path $Root ($entry.path -replace '/', '\')
        if (-not (Test-Path -LiteralPath $targetPath)) {
            continue
        }

        $bytes = [System.IO.File]::ReadAllBytes($targetPath)
        $entry.size = [int]$bytes.Length
        $entry.checksum = Get-Adler32 $bytes
    }

    $allinoneBytes = [System.IO.File]::ReadAllBytes($outputPath)
    $allinoneArtifact = [pscustomobject]@{
        path = $bundleFileName
        version = $allinoneVersion
        size = [int]$allinoneBytes.Length
        checksum = Get-Adler32 $allinoneBytes
    }

    if ($null -eq $manifest.artifacts) {
        $manifest | Add-Member -NotePropertyName artifacts -NotePropertyValue ([pscustomobject]@{}) -Force
    }

    $manifest.artifacts | Add-Member -NotePropertyName allinone -NotePropertyValue $allinoneArtifact -Force

    $json = $manifest | ConvertTo-Json -Compress -Depth 8
    [System.IO.File]::WriteAllText($manifestPath, $json, [System.Text.UTF8Encoding]::new($false))
}

$copiedToGameRoot = $false
if ($CopyToGameRoot) {
    $gameRoot = Split-Path -Parent $Root
    $gameOutputPath = Join-Path $gameRoot $allinoneFileName
    try {
        Copy-Item -LiteralPath $bootstrapPath -Destination $gameOutputPath -Force
        $copiedToGameRoot = $true
    } catch {
        Write-Warning "Could not copy all-in-one to game root: $($_.Exception.Message)"
    }
}

Write-Output ("Built {0} module(s) into {1}" -f $moduleFiles.Count, $outputPath)
Write-Output ("Built bootstrap {0}" -f $bootstrapPath)
if ($UpdateManifest) {
    Write-Output "Updated manifest.json"
}
if ($copiedToGameRoot) {
    Write-Output "Copied all-in-one to game root"
}
